---
- name: Enable Service
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - flanneld.service
    - kube-apiserver.service
    - kube-controller-manager.service
    - kube-scheduler.service
    - kube-dns.service

- name: systemd daemon-reload
  command: systemctl daemon-reload
  when: kubernetes_package_versions.changed

- name: Restart Service
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - flanneld.service
    - kube-apiserver.service
    - kube-controller-manager.service
    - kube-scheduler.service
    - kube-dns.service
